# Site settings
title: 1p Development ApS - Jacob Friis Heidelbach
email: contact@1pdevelopment.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts of a freelance consultant, moving his way through the IT industry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://1pdevelopment.com" # the base hostname & protocol for your site
twitter_username: JacobFriis
github_username:  Friischling

# Build settings
markdown: kramdown

paginate: 4

author: Jacob Friis Heidelbach

gems: [jekyll-paginate]
